package chartProgram;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.awt.Font;
//import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author yunyj99
 */
public class Chart extends javax.swing.JFrame {

    /**
     * Creates new form Chart
     */
    public Chart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlReport = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("기간결제시스템 분석프로그램");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(226, 228, 230));
        jPanel1.setName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));
        pnlReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlReport.setForeground(new java.awt.Color(234, 234, 234));
        pnlReport.setLayout(new javax.swing.BoxLayout(pnlReport, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"수강료", null, null},
                {"수강인원", null, null},
                {"수강가능인원", null, null},
                {"평균출석일", null, null},
                {"총매출", null, null},
                {"", null, null},
                {"희망 신규고객 비율", null, null},
                {"1주 미만 이용시 1회 1이용료", null, null},
                {"2주 미만 이용시 1회 1이용료", null, null},
                {"3주 미만 이용시 1회 1이용료", null, null},
                {"4주 미만 이용시 1회 1이용료", null, null},
                {"기간결제시스템 사용시 출석률", null, null}
            },
            new String [] {
                "현황자료", "입력값", "오차범위(% 단위)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(214, 214, 214));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(190);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        }

        jTabbedPane1.addTab("데이터", jScrollPane1);
        jTabbedPane1.addTab("tab2", jTabbedPane2);
        jTabbedPane1.addTab("tab3", jTabbedPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("파일");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("도움말");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("설정");
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>                        

    
    int[] inputs = new int[7]; // 입력값 저장 배열
    int[] rangeOfError = new int[7]; // 오차범위 입력값 저장 배열
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { // show 버튼 클릭하면                                  
        try {
            // 수정중인 값(테이블 셀에 포커스 되어있을 때) 저장하기
            if (jTable1.isEditing()) {
                jTable1.getCellEditor().stopCellEditing();
            }
            // 배열에 입력값 저장
            for (int i = 0; i < 5; i++) {
                int input = 0, error = 0;
				if(jTable1.getValueAt(i, 1)!=null) input = (Integer)jTable1.getValueAt(i, 1); // 입력값
				if(jTable1.getValueAt(i, 2)!=null) error = (Integer)jTable1.getValueAt(i, 2); // 오차범위


//                if (!(sInput==null)) {
//                        input = Integer.parseInt(sInput);
//                }
//                if (!(sError==null)) {
//                        if (sError.indexOf("%") != sError.length() - 1) {
//                                JOptionPane.showMessageDialog(null, "오차범위(% 단위)를 올바른 형태로 입력하세요. ex) 10%", "에러 메세지", JOptionPane.ERROR_MESSAGE);
//                        }
//                        String errorDelPercent = sError.substring(0, sError.indexOf("%")); // %기호 지운 오차범위값
//                        error = Integer.parseInt(sError);
//                        }

                 inputs[i] = input;
                 rangeOfError[i] = error;
//               System.out.println(inputs[i]);
//               System.out.println(rangeOfError[i]);
                }
        } catch (NumberFormatException nfe) {
//                JOptionPane.showMessageDialog(null, "숫자를 입력하세요", "에러 메세지", JOptionPane.ERROR_MESSAGE);
        }

        
        // 차트에 들어갈 데이터
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
            dcd.setValue(inputs[0], "result", "수강료");
            dcd.setValue(inputs[1], "result", "수강인원");
            dcd.setValue(inputs[2], "result", "수용가능인원");
            dcd.setValue(inputs[3], "result", "평균출석일");
            dcd.setValue(inputs[4], "result", "총매출");
        
        
        // 제목, X축, Y축, 데이터, 방향(수평, 수직), 범례 ....
        JFreeChart jchart = ChartFactory.createBarChart3D("Chart", "  ", "  ", dcd, PlotOrientation.VERTICAL, false, true, true);
        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);
        plot.setRangeGridlinePaint(Color.gray);
        // X 축의 라벨 설정입니다. (보조 타이틀)
        plot.getDomainAxis().setLabelFont(new Font("돋움", Font.PLAIN, 18));
        // X 축의 도메인 설정입니다.
        plot.getDomainAxis().setTickLabelFont(new Font("돋움", Font.PLAIN, 13));
        // Y 축의 라벨 설정입니다. (보조 타이틀)
        plot.getRangeAxis().setLabelFont(new Font("돋움", Font.PLAIN, 13));
        // Y 축의 도메인 설정입니다.
        plot.getRangeAxis().setTickLabelFont(new Font("돋움", Font.PLAIN, 13));


        // 새 창으로 차트 띄우기
        // 차트프레임 제목, 차트, 스크롤 펜 유무
//        ChartFrame chartFrm = new ChartFrame("Student Record", jchart, true);
//        chartFrm.setVisible(true);
//        chartFrm.setSize(500, 400);
        // 차트 패널 방식
        ChartPanel chartPanel = new ChartPanel(jchart);
        
        pnlReport.removeAll();
        pnlReport.add(chartPanel);
        pnlReport.updateUI();
    }                                        

                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlReport;
    // End of variables declaration                   
}
